# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java CI with Maven
on:
   push:
      branches:
      - master
   pull_request:
      branches:
      - master
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
      -  name: Set up JDK 11
         uses: actions/setup-java@v2
         with:
            java-version: '11'
            distribution: adopt
      -  name: Build with Maven
         run: mvn test
      -  name: Publish Test Results
         uses: EnricoMi/publish-unit-test-result-action@v1
         if: always()
         with:
            files: test-output/testng-results.xml
      -  name: Generate JaCoCo Badge
         id: jacoco
         uses: cicirello/jacoco-badge-generator@v2
         with:
            jacoco-csv-file: test-output/code-coverage/jacoco.csv
      -  name: Log coverage percentage
         run: |
            echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
            echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
      -  name: Commit the badge (if it changed)
         run: |
            if [[ `git status --porcelain` ]]; then
              git config --global user.name 'Anand Chandran'
              git config --global user.email 'anandchndrn93@users.noreply.github.com'
              git add -A
              git commit -m "Autogenerated JaCoCo coverage badge"
              git push
            fi
      -  name: Upload JaCoCo coverage report
         uses: actions/upload-artifact@v2
         with:
            name: jacoco-report
            path: test-output/code-coverage/
